# 데이터 불러오기

In [20]:
# import
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [21]:
train_walk=pd.read_csv("C:/Users/82102/Desktop/의료/128.치매 고위험군 라이프로그/128.치매 고위험군 라이프로그/01.데이터/1.Training/원천데이터/1.걸음걸이/train_activity.csv")
train_sleep=pd.read_csv("C:/Users/82102/Desktop/의료/128.치매 고위험군 라이프로그/128.치매 고위험군 라이프로그/01.데이터/1.Training/원천데이터/2.수면/train_sleep.csv")
train_think=pd.read_csv("C:/Users/82102/Desktop/의료/128.치매 고위험군 라이프로그/128.치매 고위험군 라이프로그/01.데이터/1.Training/원천데이터/3.인지기능/train_mmse.csv")

In [31]:
print(train_walk.shape, train_sleep.shape, train_think.shape)

(9705, 31) (9705, 36) (141, 38)

In [32]:
31+36+38

105

In [22]:
train_walk.columns

Index(['EMAIL', 'activity_average_met', 'activity_cal_active',
       'activity_cal_total', 'activity_class_5min', 'activity_daily_movement',
       'activity_day_end', 'activity_day_start', 'activity_high',
       'activity_inactive', 'activity_inactivity_alerts', 'activity_low',
       'activity_medium', 'activity_met_1min', 'activity_met_min_high',
       'activity_met_min_inactive', 'activity_met_min_low',
       'activity_met_min_medium', 'activity_non_wear', 'activity_rest',
       'activity_score', 'activity_score_meet_daily_targets',
       'activity_score_move_every_hour', 'activity_score_recovery_time',
       'activity_score_stay_active', 'activity_score_training_frequency',
       'activity_score_training_volume', 'activity_steps', 'activity_total',
       'CONVERT(activity_class_5min USING utf8)',
       'CONVERT(activity_met_1min USING utf8)'],
      dtype='object')

In [23]:
train_sleep.columns

Index(['EMAIL', 'sleep_awake', 'sleep_bedtime_end', 'sleep_bedtime_start',
       'sleep_breath_average', 'sleep_deep', 'sleep_duration',
       'sleep_efficiency', 'sleep_hr_5min', 'sleep_hr_average',
       'sleep_hr_lowest', 'sleep_hypnogram_5min', 'sleep_is_longest',
       'sleep_light', 'sleep_midpoint_at_delta', 'sleep_midpoint_time',
       'sleep_onset_latency', 'sleep_period_id', 'sleep_rem', 'sleep_restless',
       'sleep_rmssd', 'sleep_rmssd_5min', 'sleep_score',
       'sleep_score_alignment', 'sleep_score_deep', 'sleep_score_disturbances',
       'sleep_score_efficiency', 'sleep_score_latency', 'sleep_score_rem',
       'sleep_score_total', 'sleep_temperature_delta',
       'sleep_temperature_deviation', 'sleep_total',
       'CONVERT(sleep_hr_5min USING utf8)',
       'CONVERT(sleep_hypnogram_5min USING utf8)',
       'CONVERT(sleep_rmssd_5min USING utf8)'],
      dtype='object')

In [24]:
train_think.columns

Index(['SAMPLE_EMAIL', 'DIAG_SEQ', 'DIAG_NM', 'DOCTOR_NM', 'MMSE_NUM',
       'MMSE_KIND', 'Q01', 'Q02', 'Q03', 'Q04', 'Q05', 'Q06', 'Q07', 'Q08',
       'Q09', 'Q10', 'Q11_1', 'Q11_2', 'Q11_3', 'Q12_1', 'Q12_2', 'Q12_3',
       'Q12_4', 'Q12_5', 'Q12_TOTAL', 'Q13_1', 'Q13_2', 'Q13_3', 'Q14_1',
       'Q14_2', 'Q15', 'Q16_1', 'Q16_2', 'Q16_3', 'Q17', 'Q18', 'Q19',
       'TOTAL'],
      dtype='object')

In [25]:
train_walk['EMAIL'].nunique()

141

In [26]:
train_sleep['EMAIL'].nunique()

141

In [27]:
print(train_walk.shape, train_sleep.shape)

(9705, 31) (9705, 36)

In [28]:
train_walk.head(10)

,EMAIL,activity_average_met,activity_cal_active,activity_cal_total,activity_class_5min,activity_daily_movement,activity_day_end,activity_day_start,activity_high,activity_inactive,...,activity_score_meet_daily_targets,activity_score_move_every_hour,activity_score_recovery_time,activity_score_stay_active,activity_score_training_frequency,activity_score_training_volume,activity_steps,activity_total,CONVERT(activity_class_5min USING utf8),CONVERT(activity_met_1min USING utf8)
0,nia+279@rowan.kr,1.28125,196,2251,...,3353,2020-10-20T03:59:59+09:00,2020-10-19T04:00:00+09:00,0,714,...,78,100,100,54,100,97,4212,207,1/1/2/2/2/2/1/1/1/1/1/1/1/2/2/2/2/2/2/3/3/2/2/...,1.2/0.9/1/0.9/0.9/0.9/0.9/0.9/0.9/0.9/0.9/0.9/...
1,nia+279@rowan.kr,1.25000,145,2159,...,2516,2020-10-21T03:59:59+09:00,2020-10-20T04:00:00+09:00,0,719,...,60,100,100,58,96,96,3306,140,1/1/1/2/2/2/2/2/2/2/2/2/1/1/1/1/1/2/3/3/3/3/2/...,0.9/0.9/1.3/1/0.9/0.9/1.1/0.9/1/0.9/1/0.9/1/0....
2,nia+279@rowan.kr,1.21875,118,2140,...,1716,2020-10-22T03:59:59+09:00,2020-10-21T04:00:00+09:00,0,708,...,43,95,100,55,71,83,2550,131,1/1/1/1/1/1/1/1/1/1/1/1/1/1/1/1/1/1/1/2/3/3/3/...,0.9/0.9/0.9/0.9/0.9/0.9/0.9/0.9/0.9/0.9/0.9/0....
3,nia+279@rowan.kr,1.28125,180,2240,...,2791,2020-10-23T03:59:59+09:00,2020-10-22T04:00:00+09:00,0,705,...,43,100,100,58,71,59,4009,208,1/1/1/1/1/1/1/1/1/1/2/2/2/2/3/3/3/2/3/3/3/3/3/...,0.9/0.9/0.9/0.9/0.9/0.9/0.9/0.9/0.9/0.9/0.9/0....
4,nia+279@rowan.kr,1.46875,374,2559,...,5393,2020-10-24T03:59:59+09:00,2020-10-23T04:00:00+09:00,0,437,...,43,100,100,89,40,46,8081,517,1/1/1/2/2/2/2/2/2/1/1/1/3/2/2/1/2/2/2/3/3/2/2/...,0.9/0.9/0.9/0.9/0.9/0.9/0.9/0.9/0.9/0.9/0.9/0....
5,nia+279@rowan.kr,1.53125,436,2630,...,6860,2020-10-25T03:59:59+09:00,2020-10-24T04:00:00+09:00,0,377,...,43,100,100,95,1,45,9204,561,1/1/1/1/1/2/2/2/2/2/2/2/2/3/3/3/3/3/3/3/3/2/2/...,1.3/0.9/1/1.1/0.9/0.9/0.9/1.2/0.9/0.9/0.9/0.9/...
6,nia+279@rowan.kr,1.28125,159,2212,...,2433,2020-10-26T03:59:59+09:00,2020-10-25T04:00:00+09:00,0,679,...,43,100,100,55,1,48,3730,203,1/1/1/1/1/2/2/2/2/2/2/2/2/2/2/1/2/2/3/3/3/2/3/...,0.9/0.9/0.9/0.9/1.3/1/1/0.9/1.1/0.9/0.9/0.9/0....
7,nia+279@rowan.kr,1.28125,159,2212,...,2365,2020-10-27T03:59:59+09:00,2020-10-26T04:00:00+09:00,1,644,...,43,95,100,64,1,44,3281,197,1/1/1/1/1/1/1/1/1/1/2/3/3/3/2/3/2/2/2/2/2/2/3/...,0.9/0.9/0.9/0.9/0.9/0.9/0.9/0.9/1.3/1/0.9/1.1/...
8,nia+279@rowan.kr,1.43750,407,2508,...,7288,2020-10-28T03:59:59+09:00,2020-10-27T04:00:00+09:00,0,467,...,60,100,100,85,1,54,8050,399,1/1/1/1/1/1/1/1/1/1/1/1/1/2/2/2/2/3/2/2/3/2/3/...,0.9/0.9/0.9/0.9/0.9/0.9/0.9/0.9/0.9/0.9/0.9/0....
9,nia+279@rowan.kr,1.50000,408,2587,...,6368,2020-10-29T03:59:59+09:00,2020-10-28T04:00:00+09:00,1,438,...,78,100,100,85,40,65,8466,521,1/1/1/1/2/2/2/2/2/2/2/2/2/2/2/2/2/2/2/2/3/3/3/...,0.9/0.9/0.9/0.9/0.9/0.9/0.9/0.9/0.9/0.9/0.9/0....

In [29]:
train_sleep.head(10)

,EMAIL,sleep_awake,sleep_bedtime_end,sleep_bedtime_start,sleep_breath_average,sleep_deep,sleep_duration,sleep_efficiency,sleep_hr_5min,sleep_hr_average,...,sleep_score_efficiency,sleep_score_latency,sleep_score_rem,sleep_score_total,sleep_temperature_delta,sleep_temperature_deviation,sleep_total,CONVERT(sleep_hr_5min USING utf8),CONVERT(sleep_hypnogram_5min USING utf8),CONVERT(sleep_rmssd_5min USING utf8)
0,nia+279@rowan.kr,8700,2020-10-19T05:10:28+09:00,2020-10-18T18:38:28+09:00,17.875,10110,37920,77,...,53.04,...,65,89,56,94,0.00,0.00,29220,63/61/59/58/58/58/56/55/54/53/53/53/0/0/54/57/...,4/2/2/2/2/1/1/2/2/2/2/2/4/4/4/1/1/4/4/4/2/2/2/...,18/28/25/28/34/34/35/45/54/36/36/60/0/0/34/22/...
1,nia+279@rowan.kr,6570,2020-10-20T05:37:52+09:00,2020-10-19T21:39:52+09:00,18.000,7440,28680,77,...,52.82,...,65,97,43,65,0.34,0.34,22110,0/51/0/51/52/52/52/52/53/53/53/52/52/53/53/53/...,4/2/4/2/2/2/1/1/1/2/2/3/3/3/3/3/3/3/1/1/1/4/4/...,0/49/0/38/51/17/18/18/26/27/24/29/36/31/32/34/...
2,nia+279@rowan.kr,10530,2020-10-21T05:45:28+09:00,2020-10-20T20:51:28+09:00,18.000,4620,32040,67,...,52.01,...,41,75,68,62,-0.07,-0.07,21510,54/56/0/55/53/55/56/55/0/55/54/54/54/0/0/55/55...,4/2/1/1/2/2/4/4/4/4/2/2/2/4/4/4/2/4/4/4/4/4/4/...,56/47/0/49/42/57/44/49/0/46/54/47/55/0/0/55/53...
3,nia+279@rowan.kr,4080,2020-10-22T05:12:16+09:00,2020-10-21T22:08:16+09:00,17.500,7440,25440,84,...,51.07,...,81,83,73,62,-0.14,-0.14,21360,0/54/53/53/54/54/54/53/53/53/53/54/51/50/51/51...,4/4/1/1/1/1/1/1/1/1/1/4/2/2/2/2/1/1/1/1/1/4/2/...,0/40/40/40/37/46/35/46/44/56/50/48/41/55/55/50...
4,nia+279@rowan.kr,7170,2020-10-23T02:23:30+09:00,2020-10-22T20:38:30+09:00,17.875,4320,20700,65,...,50.80,...,39,78,25,29,-0.50,-0.50,13530,0/49/50/50/50/50/50/50/51/0/0/0/0/0/0/0/0/50/5...,4/2/2/2/2/1/1/1/2/4/4/4/4/4/4/4/4/4/2/1/1/1/1/...,0/81/60/74/62/63/56/78/81/0/0/0/0/0/0/0/0/60/4...
5,nia+279@rowan.kr,2850,2020-10-24T04:49:37+09:00,2020-10-23T21:16:37+09:00,19.000,7290,27180,90,...,59.68,...,95,70,71,74,-0.14,-0.14,24330,61/61/60/60/60/62/62/61/61/61/61/61/64/63/61/6...,4/2/2/1/1/1/2/1/1/1/1/1/3/3/3/3/3/3/3/3/3/3/1/...,28/36/29/36/33/30/26/26/25/29/27/28/24/23/24/2...
6,nia+279@rowan.kr,3930,2020-10-25T04:30:09+09:00,2020-10-24T20:36:09+09:00,18.000,5820,28440,86,...,53.79,...,86,97,76,75,0.62,0.62,24510,0/0/0/57/58/57/58/0/0/55/55/54/54/0/53/54/0/0/...,4/4/4/2/1/1/2/4/2/2/2/2/2/4/3/3/3/3/3/2/2/2/4/...,0/0/0/33/41/41/37/0/0/22/43/26/21/0/66/84/0/0/...
7,nia+279@rowan.kr,1380,2020-10-26T04:57:32+09:00,2020-10-25T21:19:32+09:00,18.250,9750,27480,95,...,54.16,...,100,97,55,81,-0.06,-0.06,26100,0/56/56/55/55/55/55/56/56/58/57/58/59/55/56/56...,4/2/4/2/2/1/1/1/1/1/1/1/2/2/1/1/1/1/1/2/2/2/2/...,0/50/44/46/40/39/48/39/47/42/45/50/41/47/44/40...
8,nia+279@rowan.kr,5610,2020-10-27T05:10:35+09:00,2020-10-26T21:53:35+09:00,17.625,6660,26220,79,...,49.63,...,69,83,47,59,-0.05,-0.05,20610,0/0/0/0/48/48/0/0/0/0/0/49/47/48/49/50/50/51/5...,4/4/4/4/2/2/4/4/4/4/4/2/2/1/1/1/1/2/2/1/2/1/2/...,0/0/0/0/54/68/0/0/0/0/0/68/82/66/52/62/44/40/4...
9,nia+279@rowan.kr,6180,2020-10-28T04:26:40+09:00,2020-10-27T19:50:40+09:00,17.875,7020,30960,80,...,51.98,...,72,97,28,76,0.51,0.51,24780,0/0/0/65/63/61/61/59/58/0/56/54/54/53/54/54/0/...,4/4/4/2/1/1/2/2/4/4/2/2/2/1/1/4/4/4/4/4/4/4/4/...,0/0/0/22/21/22/18/26/26/0/30/34/38/38/41/41/0/...

## EMAIL 기준으로 데이터 병합

In [30]:
train_walk['EMAIL']==train_sleep['EMAIL']

0       True
1       True
2       True
3       True
4       True
        ...
9700    True
9701    True
9702    True
9703    True
9704    True
Name: EMAIL, Length: 9705, dtype: bool

In [12]:
comparison_series = train_walk['EMAIL'] == train_sleep['EMAIL']

if False in comparison_series.values:
    print("FALSE")
else:
    print("TRUE")

TRUE

In [13]:
train_data=pd.concat([train_walk,train_sleep],axis=1)
train_data

,EMAIL,activity_average_met,activity_cal_active,activity_cal_total,activity_class_5min,activity_daily_movement,activity_day_end,activity_day_start,activity_high,activity_inactive,...,sleep_score_efficiency,sleep_score_latency,sleep_score_rem,sleep_score_total,sleep_temperature_delta,sleep_temperature_deviation,sleep_total,CONVERT(sleep_hr_5min USING utf8),CONVERT(sleep_hypnogram_5min USING utf8),CONVERT(sleep_rmssd_5min USING utf8)
0,nia+279@rowan.kr,1.28125,196,2251,...,3353,2020-10-20T03:59:59+09:00,2020-10-19T04:00:00+09:00,0,714,...,65,89,56,94,0.00,0.00,29220,63/61/59/58/58/58/56/55/54/53/53/53/0/0/54/57/...,4/2/2/2/2/1/1/2/2/2/2/2/4/4/4/1/1/4/4/4/2/2/2/...,18/28/25/28/34/34/35/45/54/36/36/60/0/0/34/22/...
1,nia+279@rowan.kr,1.25000,145,2159,...,2516,2020-10-21T03:59:59+09:00,2020-10-20T04:00:00+09:00,0,719,...,65,97,43,65,0.34,0.34,22110,0/51/0/51/52/52/52/52/53/53/53/52/52/53/53/53/...,4/2/4/2/2/2/1/1/1/2/2/3/3/3/3/3/3/3/1/1/1/4/4/...,0/49/0/38/51/17/18/18/26/27/24/29/36/31/32/34/...
2,nia+279@rowan.kr,1.21875,118,2140,...,1716,2020-10-22T03:59:59+09:00,2020-10-21T04:00:00+09:00,0,708,...,41,75,68,62,-0.07,-0.07,21510,54/56/0/55/53/55/56/55/0/55/54/54/54/0/0/55/55...,4/2/1/1/2/2/4/4/4/4/2/2/2/4/4/4/2/4/4/4/4/4/4/...,56/47/0/49/42/57/44/49/0/46/54/47/55/0/0/55/53...
3,nia+279@rowan.kr,1.28125,180,2240,...,2791,2020-10-23T03:59:59+09:00,2020-10-22T04:00:00+09:00,0,705,...,81,83,73,62,-0.14,-0.14,21360,0/54/53/53/54/54/54/53/53/53/53/54/51/50/51/51...,4/4/1/1/1/1/1/1/1/1/1/4/2/2/2/2/1/1/1/1/1/4/2/...,0/40/40/40/37/46/35/46/44/56/50/48/41/55/55/50...
4,nia+279@rowan.kr,1.46875,374,2559,...,5393,2020-10-24T03:59:59+09:00,2020-10-23T04:00:00+09:00,0,437,...,39,78,25,29,-0.50,-0.50,13530,0/49/50/50/50/50/50/50/51/0/0/0/0/0/0/0/0/50/5...,4/2/2/2/2/1/1/1/2/4/4/4/4/4/4/4/4/4/2/1/1/1/1/...,0/81/60/74/62/63/56/78/81/0/0/0/0/0/0/0/0/60/4...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9700,nia+206@rowan.kr,1.34375,249,2351,...,4411,2020-12-25T03:59:59+09:00,2020-12-24T04:00:00+09:00,1,780,...,76,81,95,86,-0.09,-0.09,27360,68/66/67/67/68/69/69/70/71/71/71/69/72/70/70/7...,4/4/2/2/2/1/1/1/1/1/1/2/2/3/3/2/2/2/2/2/3/4/2/...,26/16/19/18/16/18/19/17/15/16/15/13/11/13/13/1...
9701,nia+206@rowan.kr,1.53125,570,2682,...,11057,2020-12-27T03:59:59+09:00,2020-12-26T04:00:00+09:00,1,518,...,69,86,89,64,0.41,0.41,22020,0/0/65/65/66/67/69/72/73/72/73/74/73/74/75/75/...,4/4/2/2/2/2/2/2/2/2/2/2/4/4/4/4/2/3/3/3/2/2/4/...,0/0/13/12/12/13/12/12/12/16/13/12/13/17/13/18/...
9702,nia+206@rowan.kr,1.34375,295,2331,...,5135,2020-12-28T03:59:59+09:00,2020-12-27T04:00:00+09:00,4,578,...,86,89,98,97,0.27,0.27,30390,0/0/0/64/64/64/64/65/65/66/66/66/66/68/68/68/6...,4/4/4/4/2/2/2/2/2/2/2/2/2/3/3/3/3/2/4/4/2/2/2/...,0/0/0/14/17/18/14/14/17/15/17/12/17/12/13/12/1...
9703,nia+206@rowan.kr,1.31250,186,2280,...,3178,2020-12-29T03:59:59+09:00,2020-12-28T04:00:00+09:00,0,778,...,98,89,86,80,-0.05,-0.05,25800,0/60/60/61/60/60/60/62/64/64/64/64/65/68/70/70...,4/4/1/2/2/2/2/1/2/2/2/1/1/1/3/3/1/1/2/2/3/3/3/...,0/14/15/14/15/16/17/16/16/18/18/20/23/15/21/20...
9704,nia+206@rowan.kr,1.37500,83,1891,...,1554,2020-12-30T03:59:59+09:00,2020-12-29T04:00:00+09:00,0,69,...,88,99,76,66,0.26,0.26,22470,0/0/0/62/62/62/61/60/60/61/61/62/0/67/66/66/66...,4/4/4/2/2/2/2/2/2/2/2/2/3/3/3/3/3/2/2/2/2/2/2/...,0/0/0/19/18/22/20/16/16/16/14/18/0/36/28/23/21...

# 결측 열 제거

In [14]:
train_data=train_data.drop(train_data.columns[[4,13,39,42,52]], axis=1)
train_data

,EMAIL,activity_average_met,activity_cal_active,activity_cal_total,activity_daily_movement,activity_day_end,activity_day_start,activity_high,activity_inactive,activity_inactivity_alerts,...,sleep_score_efficiency,sleep_score_latency,sleep_score_rem,sleep_score_total,sleep_temperature_delta,sleep_temperature_deviation,sleep_total,CONVERT(sleep_hr_5min USING utf8),CONVERT(sleep_hypnogram_5min USING utf8),CONVERT(sleep_rmssd_5min USING utf8)
0,nia+279@rowan.kr,1.28125,196,2251,3353,2020-10-20T03:59:59+09:00,2020-10-19T04:00:00+09:00,0,714,0,...,65,89,56,94,0.00,0.00,29220,63/61/59/58/58/58/56/55/54/53/53/53/0/0/54/57/...,4/2/2/2/2/1/1/2/2/2/2/2/4/4/4/1/1/4/4/4/2/2/2/...,18/28/25/28/34/34/35/45/54/36/36/60/0/0/34/22/...
1,nia+279@rowan.kr,1.25000,145,2159,2516,2020-10-21T03:59:59+09:00,2020-10-20T04:00:00+09:00,0,719,0,...,65,97,43,65,0.34,0.34,22110,0/51/0/51/52/52/52/52/53/53/53/52/52/53/53/53/...,4/2/4/2/2/2/1/1/1/2/2/3/3/3/3/3/3/3/1/1/1/4/4/...,0/49/0/38/51/17/18/18/26/27/24/29/36/31/32/34/...
2,nia+279@rowan.kr,1.21875,118,2140,1716,2020-10-22T03:59:59+09:00,2020-10-21T04:00:00+09:00,0,708,1,...,41,75,68,62,-0.07,-0.07,21510,54/56/0/55/53/55/56/55/0/55/54/54/54/0/0/55/55...,4/2/1/1/2/2/4/4/4/4/2/2/2/4/4/4/2/4/4/4/4/4/4/...,56/47/0/49/42/57/44/49/0/46/54/47/55/0/0/55/53...
3,nia+279@rowan.kr,1.28125,180,2240,2791,2020-10-23T03:59:59+09:00,2020-10-22T04:00:00+09:00,0,705,0,...,81,83,73,62,-0.14,-0.14,21360,0/54/53/53/54/54/54/53/53/53/53/54/51/50/51/51...,4/4/1/1/1/1/1/1/1/1/1/4/2/2/2/2/1/1/1/1/1/4/2/...,0/40/40/40/37/46/35/46/44/56/50/48/41/55/55/50...
4,nia+279@rowan.kr,1.46875,374,2559,5393,2020-10-24T03:59:59+09:00,2020-10-23T04:00:00+09:00,0,437,0,...,39,78,25,29,-0.50,-0.50,13530,0/49/50/50/50/50/50/50/51/0/0/0/0/0/0/0/0/50/5...,4/2/2/2/2/1/1/1/2/4/4/4/4/4/4/4/4/4/2/1/1/1/1/...,0/81/60/74/62/63/56/78/81/0/0/0/0/0/0/0/0/60/4...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9700,nia+206@rowan.kr,1.34375,249,2351,4411,2020-12-25T03:59:59+09:00,2020-12-24T04:00:00+09:00,1,780,4,...,76,81,95,86,-0.09,-0.09,27360,68/66/67/67/68/69/69/70/71/71/71/69/72/70/70/7...,4/4/2/2/2/1/1/1/1/1/1/2/2/3/3/2/2/2/2/2/3/4/2/...,26/16/19/18/16/18/19/17/15/16/15/13/11/13/13/1...
9701,nia+206@rowan.kr,1.53125,570,2682,11057,2020-12-27T03:59:59+09:00,2020-12-26T04:00:00+09:00,1,518,1,...,69,86,89,64,0.41,0.41,22020,0/0/65/65/66/67/69/72/73/72/73/74/73/74/75/75/...,4/4/2/2/2/2/2/2/2/2/2/2/4/4/4/4/2/3/3/3/2/2/4/...,0/0/13/12/12/13/12/12/12/16/13/12/13/17/13/18/...
9702,nia+206@rowan.kr,1.34375,295,2331,5135,2020-12-28T03:59:59+09:00,2020-12-27T04:00:00+09:00,4,578,0,...,86,89,98,97,0.27,0.27,30390,0/0/0/64/64/64/64/65/65/66/66/66/66/68/68/68/6...,4/4/4/4/2/2/2/2/2/2/2/2/2/3/3/3/3/2/4/4/2/2/2/...,0/0/0/14/17/18/14/14/17/15/17/12/17/12/13/12/1...
9703,nia+206@rowan.kr,1.31250,186,2280,3178,2020-12-29T03:59:59+09:00,2020-12-28T04:00:00+09:00,0,778,1,...,98,89,86,80,-0.05,-0.05,25800,0/60/60/61/60/60/60/62/64/64/64/64/65/68/70/70...,4/4/1/2/2/2/2/1/2/2/2/1/1/1/3/3/1/1/2/2/3/3/3/...,0/14/15/14/15/16/17/16/16/18/18/20/23/15/21/20...
9704,nia+206@rowan.kr,1.37500,83,1891,1554,2020-12-30T03:59:59+09:00,2020-12-29T04:00:00+09:00,0,69,0,...,88,99,76,66,0.26,0.26,22470,0/0/0/62/62/62/61/60/60/61/61/62/0/67/66/66/66...,4/4/4/2/2/2/2/2/2/2/2/2/3/3/3/3/3/2/2/2/2/2/2/...,0/0/0/19/18/22/20/16/16/16/14/18/0/36/28/23/21...

In [15]:
train_data = train_data.loc[:,~train_data.columns.duplicated()] # 중복되는 EMAIl 열 하나만 남기고 하나만 제거
train_data

,EMAIL,activity_average_met,activity_cal_active,activity_cal_total,activity_daily_movement,activity_day_end,activity_day_start,activity_high,activity_inactive,activity_inactivity_alerts,...,sleep_score_efficiency,sleep_score_latency,sleep_score_rem,sleep_score_total,sleep_temperature_delta,sleep_temperature_deviation,sleep_total,CONVERT(sleep_hr_5min USING utf8),CONVERT(sleep_hypnogram_5min USING utf8),CONVERT(sleep_rmssd_5min USING utf8)
0,nia+279@rowan.kr,1.28125,196,2251,3353,2020-10-20T03:59:59+09:00,2020-10-19T04:00:00+09:00,0,714,0,...,65,89,56,94,0.00,0.00,29220,63/61/59/58/58/58/56/55/54/53/53/53/0/0/54/57/...,4/2/2/2/2/1/1/2/2/2/2/2/4/4/4/1/1/4/4/4/2/2/2/...,18/28/25/28/34/34/35/45/54/36/36/60/0/0/34/22/...
1,nia+279@rowan.kr,1.25000,145,2159,2516,2020-10-21T03:59:59+09:00,2020-10-20T04:00:00+09:00,0,719,0,...,65,97,43,65,0.34,0.34,22110,0/51/0/51/52/52/52/52/53/53/53/52/52/53/53/53/...,4/2/4/2/2/2/1/1/1/2/2/3/3/3/3/3/3/3/1/1/1/4/4/...,0/49/0/38/51/17/18/18/26/27/24/29/36/31/32/34/...
2,nia+279@rowan.kr,1.21875,118,2140,1716,2020-10-22T03:59:59+09:00,2020-10-21T04:00:00+09:00,0,708,1,...,41,75,68,62,-0.07,-0.07,21510,54/56/0/55/53/55/56/55/0/55/54/54/54/0/0/55/55...,4/2/1/1/2/2/4/4/4/4/2/2/2/4/4/4/2/4/4/4/4/4/4/...,56/47/0/49/42/57/44/49/0/46/54/47/55/0/0/55/53...
3,nia+279@rowan.kr,1.28125,180,2240,2791,2020-10-23T03:59:59+09:00,2020-10-22T04:00:00+09:00,0,705,0,...,81,83,73,62,-0.14,-0.14,21360,0/54/53/53/54/54/54/53/53/53/53/54/51/50/51/51...,4/4/1/1/1/1/1/1/1/1/1/4/2/2/2/2/1/1/1/1/1/4/2/...,0/40/40/40/37/46/35/46/44/56/50/48/41/55/55/50...
4,nia+279@rowan.kr,1.46875,374,2559,5393,2020-10-24T03:59:59+09:00,2020-10-23T04:00:00+09:00,0,437,0,...,39,78,25,29,-0.50,-0.50,13530,0/49/50/50/50/50/50/50/51/0/0/0/0/0/0/0/0/50/5...,4/2/2/2/2/1/1/1/2/4/4/4/4/4/4/4/4/4/2/1/1/1/1/...,0/81/60/74/62/63/56/78/81/0/0/0/0/0/0/0/0/60/4...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9700,nia+206@rowan.kr,1.34375,249,2351,4411,2020-12-25T03:59:59+09:00,2020-12-24T04:00:00+09:00,1,780,4,...,76,81,95,86,-0.09,-0.09,27360,68/66/67/67/68/69/69/70/71/71/71/69/72/70/70/7...,4/4/2/2/2/1/1/1/1/1/1/2/2/3/3/2/2/2/2/2/3/4/2/...,26/16/19/18/16/18/19/17/15/16/15/13/11/13/13/1...
9701,nia+206@rowan.kr,1.53125,570,2682,11057,2020-12-27T03:59:59+09:00,2020-12-26T04:00:00+09:00,1,518,1,...,69,86,89,64,0.41,0.41,22020,0/0/65/65/66/67/69/72/73/72/73/74/73/74/75/75/...,4/4/2/2/2/2/2/2/2/2/2/2/4/4/4/4/2/3/3/3/2/2/4/...,0/0/13/12/12/13/12/12/12/16/13/12/13/17/13/18/...
9702,nia+206@rowan.kr,1.34375,295,2331,5135,2020-12-28T03:59:59+09:00,2020-12-27T04:00:00+09:00,4,578,0,...,86,89,98,97,0.27,0.27,30390,0/0/0/64/64/64/64/65/65/66/66/66/66/68/68/68/6...,4/4/4/4/2/2/2/2/2/2/2/2/2/3/3/3/3/2/4/4/2/2/2/...,0/0/0/14/17/18/14/14/17/15/17/12/17/12/13/12/1...
9703,nia+206@rowan.kr,1.31250,186,2280,3178,2020-12-29T03:59:59+09:00,2020-12-28T04:00:00+09:00,0,778,1,...,98,89,86,80,-0.05,-0.05,25800,0/60/60/61/60/60/60/62/64/64/64/64/65/68/70/70...,4/4/1/2/2/2/2/1/2/2/2/1/1/1/3/3/1/1/2/2/3/3/3/...,0/14/15/14/15/16/17/16/16/18/18/20/23/15/21/20...
9704,nia+206@rowan.kr,1.37500,83,1891,1554,2020-12-30T03:59:59+09:00,2020-12-29T04:00:00+09:00,0,69,0,...,88,99,76,66,0.26,0.26,22470,0/0/0/62/62/62/61/60/60/61/61/62/0/67/66/66/66...,4/4/4/2/2/2/2/2/2/2/2/2/3/3/3/3/3/2/2/2/2/2/2/...,0/0/0/19/18/22/20/16/16/16/14/18/0/36/28/23/21...

In [16]:
train_merged_data = pd.merge(train_data, train_think, left_on='EMAIL', right_on='SAMPLE_EMAIL', how='inner')
train_merged_data

,EMAIL,activity_average_met,activity_cal_active,activity_cal_total,activity_daily_movement,activity_day_end,activity_day_start,activity_high,activity_inactive,activity_inactivity_alerts,...,Q14_1,Q14_2,Q15,Q16_1,Q16_2,Q16_3,Q17,Q18,Q19,TOTAL
0,nia+279@rowan.kr,1.28125,196,2251,3353,2020-10-20T03:59:59+09:00,2020-10-19T04:00:00+09:00,0,714,0,...,2,2,1,1,2,2,1,2,2,17
1,nia+279@rowan.kr,1.25000,145,2159,2516,2020-10-21T03:59:59+09:00,2020-10-20T04:00:00+09:00,0,719,0,...,2,2,1,1,2,2,1,2,2,17
2,nia+279@rowan.kr,1.21875,118,2140,1716,2020-10-22T03:59:59+09:00,2020-10-21T04:00:00+09:00,0,708,1,...,2,2,1,1,2,2,1,2,2,17
3,nia+279@rowan.kr,1.28125,180,2240,2791,2020-10-23T03:59:59+09:00,2020-10-22T04:00:00+09:00,0,705,0,...,2,2,1,1,2,2,1,2,2,17
4,nia+279@rowan.kr,1.46875,374,2559,5393,2020-10-24T03:59:59+09:00,2020-10-23T04:00:00+09:00,0,437,0,...,2,2,1,1,2,2,1,2,2,17
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9700,nia+206@rowan.kr,1.34375,249,2351,4411,2020-12-25T03:59:59+09:00,2020-12-24T04:00:00+09:00,1,780,4,...,2,2,2,2,2,2,1,2,2,28
9701,nia+206@rowan.kr,1.53125,570,2682,11057,2020-12-27T03:59:59+09:00,2020-12-26T04:00:00+09:00,1,518,1,...,2,2,2,2,2,2,1,2,2,28
9702,nia+206@rowan.kr,1.34375,295,2331,5135,2020-12-28T03:59:59+09:00,2020-12-27T04:00:00+09:00,4,578,0,...,2,2,2,2,2,2,1,2,2,28
9703,nia+206@rowan.kr,1.31250,186,2280,3178,2020-12-29T03:59:59+09:00,2020-12-28T04:00:00+09:00,0,778,1,...,2,2,2,2,2,2,1,2,2,28
9704,nia+206@rowan.kr,1.37500,83,1891,1554,2020-12-30T03:59:59+09:00,2020-12-29T04:00:00+09:00,0,69,0,...,2,2,2,2,2,2,1,2,2,28

In [17]:
# 결측치 DOCTOR_NM 열 제거
train_merged_data.drop(['DOCTOR_NM'], axis=1, inplace=True)
train_merged_data

,EMAIL,activity_average_met,activity_cal_active,activity_cal_total,activity_daily_movement,activity_day_end,activity_day_start,activity_high,activity_inactive,activity_inactivity_alerts,...,Q14_1,Q14_2,Q15,Q16_1,Q16_2,Q16_3,Q17,Q18,Q19,TOTAL
0,nia+279@rowan.kr,1.28125,196,2251,3353,2020-10-20T03:59:59+09:00,2020-10-19T04:00:00+09:00,0,714,0,...,2,2,1,1,2,2,1,2,2,17
1,nia+279@rowan.kr,1.25000,145,2159,2516,2020-10-21T03:59:59+09:00,2020-10-20T04:00:00+09:00,0,719,0,...,2,2,1,1,2,2,1,2,2,17
2,nia+279@rowan.kr,1.21875,118,2140,1716,2020-10-22T03:59:59+09:00,2020-10-21T04:00:00+09:00,0,708,1,...,2,2,1,1,2,2,1,2,2,17
3,nia+279@rowan.kr,1.28125,180,2240,2791,2020-10-23T03:59:59+09:00,2020-10-22T04:00:00+09:00,0,705,0,...,2,2,1,1,2,2,1,2,2,17
4,nia+279@rowan.kr,1.46875,374,2559,5393,2020-10-24T03:59:59+09:00,2020-10-23T04:00:00+09:00,0,437,0,...,2,2,1,1,2,2,1,2,2,17
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9700,nia+206@rowan.kr,1.34375,249,2351,4411,2020-12-25T03:59:59+09:00,2020-12-24T04:00:00+09:00,1,780,4,...,2,2,2,2,2,2,1,2,2,28
9701,nia+206@rowan.kr,1.53125,570,2682,11057,2020-12-27T03:59:59+09:00,2020-12-26T04:00:00+09:00,1,518,1,...,2,2,2,2,2,2,1,2,2,28
9702,nia+206@rowan.kr,1.34375,295,2331,5135,2020-12-28T03:59:59+09:00,2020-12-27T04:00:00+09:00,4,578,0,...,2,2,2,2,2,2,1,2,2,28
9703,nia+206@rowan.kr,1.31250,186,2280,3178,2020-12-29T03:59:59+09:00,2020-12-28T04:00:00+09:00,0,778,1,...,2,2,2,2,2,2,1,2,2,28
9704,nia+206@rowan.kr,1.37500,83,1891,1554,2020-12-30T03:59:59+09:00,2020-12-29T04:00:00+09:00,0,69,0,...,2,2,2,2,2,2,1,2,2,28

In [19]:
train_merged_data.columns

Index(['EMAIL', 'activity_average_met', 'activity_cal_active',
       'activity_cal_total', 'activity_daily_movement', 'activity_day_end',
       'activity_day_start', 'activity_high', 'activity_inactive',
       'activity_inactivity_alerts', 'activity_low', 'activity_medium',
       'activity_met_min_high', 'activity_met_min_inactive',
       'activity_met_min_low', 'activity_met_min_medium', 'activity_non_wear',
       'activity_rest', 'activity_score', 'activity_score_meet_daily_targets',
       'activity_score_move_every_hour', 'activity_score_recovery_time',
       'activity_score_stay_active', 'activity_score_training_frequency',
       'activity_score_training_volume', 'activity_steps', 'activity_total',
       'CONVERT(activity_class_5min USING utf8)',
       'CONVERT(activity_met_1min USING utf8)', 'sleep_awake',
       'sleep_bedtime_end', 'sleep_bedtime_start', 'sleep_breath_average',
       'sleep_deep', 'sleep_duration', 'sleep_efficiency', 'sleep_hr_average',
       'sleep_hr_lowest', 'sleep_is_longest', 'sleep_light',
       'sleep_midpoint_at_delta', 'sleep_midpoint_time', 'sleep_onset_latency',
       'sleep_period_id', 'sleep_rem', 'sleep_restless', 'sleep_rmssd',
       'sleep_score', 'sleep_score_alignment', 'sleep_score_deep',
       'sleep_score_disturbances', 'sleep_score_efficiency',
       'sleep_score_latency', 'sleep_score_rem', 'sleep_score_total',
       'sleep_temperature_delta', 'sleep_temperature_deviation', 'sleep_total',
       'CONVERT(sleep_hr_5min USING utf8)',
       'CONVERT(sleep_hypnogram_5min USING utf8)',
       'CONVERT(sleep_rmssd_5min USING utf8)', 'SAMPLE_EMAIL', 'DIAG_SEQ',
       'DIAG_NM', 'MMSE_NUM', 'MMSE_KIND', 'Q01', 'Q02', 'Q03', 'Q04', 'Q05',
       'Q06', 'Q07', 'Q08', 'Q09', 'Q10', 'Q11_1', 'Q11_2', 'Q11_3', 'Q12_1',
       'Q12_2', 'Q12_3', 'Q12_4', 'Q12_5', 'Q12_TOTAL', 'Q13_1', 'Q13_2',
       'Q13_3', 'Q14_1', 'Q14_2', 'Q15', 'Q16_1', 'Q16_2', 'Q16_3', 'Q17',
       'Q18', 'Q19', 'TOTAL'],
      dtype='object')

In [33]:
train_merged_data['activity_non_wear']

0         0
1       117
2         0
3        85
4        33
       ...
9700      0
9701      0
9702      0
9703    113
9704     38
Name: activity_non_wear, Length: 9705, dtype: int64

# train 데이터 병합 최종파일

In [45]:
train_merged_data.to_csv("C:/Users/82102/Desktop/의료/128.치매 고위험군 라이프로그/128.치매 고위험군 라이프로그/01.데이터/train_data.csv")

# validation 데이터 병합

In [46]:
val_walk=pd.read_csv("C:/Users/82102/Desktop/의료/128.치매 고위험군 라이프로그/128.치매 고위험군 라이프로그/01.데이터/2.Validation/원천데이터/1.걸음걸이/val_activity.csv")
val_sleep=pd.read_csv("C:/Users/82102/Desktop/의료/128.치매 고위험군 라이프로그/128.치매 고위험군 라이프로그/01.데이터/2.Validation/원천데이터/2.수면/val_sleep.csv")
val_think=pd.read_csv("C:/Users/82102/Desktop/의료/128.치매 고위험군 라이프로그/128.치매 고위험군 라이프로그/01.데이터/2.Validation/원천데이터/3.인지기능/val_mmse.csv")

In [47]:
val_walk

,EMAIL,activity_average_met,activity_cal_active,activity_cal_total,activity_class_5min,activity_daily_movement,activity_day_end,activity_day_start,activity_high,activity_inactive,...,activity_score_meet_daily_targets,activity_score_move_every_hour,activity_score_recovery_time,activity_score_stay_active,activity_score_training_frequency,activity_score_training_volume,activity_steps,activity_total,CONVERT(activity_class_5min USING utf8),CONVERT(activity_met_1min USING utf8)
0,nia+404@rowan.kr,1.71875,730,2944,...,14346,2020-11-28T03:59:59+09:00,2020-11-27T04:00:00+09:00,0,417,...,95,100,100,86,100,98,15867,592,2/1/1/1/1/1/2/2/1/1/1/1/1/1/2/2/2/3/2/2/2/2/2/...,0.9/0.9/1.4/1.9/1.1/0.9/0.9/1.1/1.3/1/0.9/1.1/...
1,nia+404@rowan.kr,1.40625,342,2449,...,6352,2020-11-29T03:59:59+09:00,2020-11-28T04:00:00+09:00,0,473,...,78,100,100,83,100,97,7755,400,1/1/1/1/1/1/1/1/1/1/1/1/1/1/1/1/1/2/2/2/2/2/2/...,1.2/1.1/0.9/0.9/0.9/0.9/0.9/0.9/0.9/0.9/0.9/0....
2,nia+404@rowan.kr,1.46875,401,2544,...,7297,2020-11-30T03:59:59+09:00,2020-11-29T04:00:00+09:00,0,586,...,95,100,100,71,96,96,8341,386,1/1/1/1/1/1/1/2/1/1/1/1/2/2/2/2/2/1/1/1/1/1/2/...,1.1/1.1/1.2/1.1/0.9/0.9/0.9/0.9/0.9/0.9/0.9/0....
3,nia+404@rowan.kr,0.34375,27,1850,...,491,2020-12-01T03:59:59+09:00,2020-11-30T04:00:00+09:00,0,176,...,95,100,100,74,96,92,8122,35,2/1/2/2/1/2/1/1/2/1/1/1/1/1/2/1/1/1/1/1/2/2/2/...,0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/...
4,nia+404@rowan.kr,1.46875,333,2518,...,5861,2020-12-02T03:59:59+09:00,2020-12-01T04:00:00+09:00,0,646,...,95,100,100,65,71,80,7378,383,1/1/1/1/1/1/1/1/1/1/1/1/1/1/1/1/1/1/2/2/3/3/2/...,0.9/0.9/0.9/0.9/0.9/0.9/0.9/0.9/0.9/0.9/0.9/0....
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2473,nia+280@rowan.kr,1.59375,648,2760,...,12256,2021-02-13T03:59:59+09:00,2021-02-12T04:00:00+09:00,0,444,...,100,100,95,88,100,100,14654,447,1/2/1/1/1/2/2/3/3/2/5/3/2/2/2/2/2/1/2/1/1/1/1/...,1.2/0.9/0.9/0.9/1.1/1.1/0.9/1.1/2.4/0.9/0.9/0....
2474,nia+280@rowan.kr,1.43750,379,2507,...,6973,2021-02-14T03:59:59+09:00,2021-02-13T04:00:00+09:00,0,623,...,100,100,89,65,100,99,8425,374,1/1/1/1/1/2/2/2/3/3/4/2/2/2/2/1/2/2/1/1/1/2/1/...,0.9/0.9/0.9/0.9/0.9/0.9/0.9/0.9/0.9/0.9/0.9/0....
2475,nia+280@rowan.kr,1.56250,670,2747,...,13008,2021-02-16T03:59:59+09:00,2021-02-15T04:00:00+09:00,0,422,...,100,100,100,95,100,99,15341,442,3/3/3/3/3/2/3/3/2/2/2/2/2/2/2/2/2/2/2/2/1/2/1/...,2.1/1.9/2.2/2.4/2.8/2.2/1.9/1.7/1.9/1.4/2.6/1....
2476,nia+280@rowan.kr,1.46875,556,2570,...,11043,2021-02-17T03:59:59+09:00,2021-02-16T04:00:00+09:00,0,452,...,100,78,95,87,100,100,12006,312,1/1/1/1/1/1/1/1/1/1/1/1/1/1/1/1/1/1/1/1/1/1/1/...,0.9/0.9/0.9/0.9/0.9/0.9/0.9/0.9/0.9/0.9/0.9/0....
2477,nia+280@rowan.kr,1.34375,311,2341,...,5943,2021-02-18T03:59:59+09:00,2021-02-17T04:00:00+09:00,0,595,...,100,100,89,67,100,99,6691,294,1/1/1/1/1/1/1/1/1/1/1/1/1/1/1/1/1/1/1/1/1/1/1/...,1.3/0.9/0.9/0.9/0.9/0.9/0.9/0.9/0.9/0.9/0.9/0....

In [48]:
comparison_series = val_walk['EMAIL'] == val_sleep['EMAIL']

if False in comparison_series.values:
    print("FALSE")
else:
    print("TRUE")

TRUE

In [49]:
val_data=pd.concat([val_walk,val_sleep],axis=1)
val_data

,EMAIL,activity_average_met,activity_cal_active,activity_cal_total,activity_class_5min,activity_daily_movement,activity_day_end,activity_day_start,activity_high,activity_inactive,...,sleep_score_efficiency,sleep_score_latency,sleep_score_rem,sleep_score_total,sleep_temperature_delta,sleep_temperature_deviation,sleep_total,CONVERT(sleep_hr_5min USING utf8),CONVERT(sleep_hypnogram_5min USING utf8),CONVERT(sleep_rmssd_5min USING utf8)
0,nia+404@rowan.kr,1.71875,730,2944,...,14346,2020-11-28T03:59:59+09:00,2020-11-27T04:00:00+09:00,0,417,...,27,97,66,62,-0.12,-0.12,21510,0/73/73/73/72/71/70/71/71/71/70/70/73/72/74/74...,4/2/4/3/3/1/2/2/2/2/2/2/3/3/3/4/4/3/2/2/2/2/2/...,0/10/10/10/11/11/10/12/18/13/14/12/10/10/18/17...
1,nia+404@rowan.kr,1.40625,342,2449,...,6352,2020-11-29T03:59:59+09:00,2020-11-28T04:00:00+09:00,0,473,...,46,91,35,44,-0.32,-0.32,17040,69/70/69/69/70/72/71/72/70/69/69/69/68/68/63/6...,2/4/2/2/2/2/3/1/2/2/4/4/2/2/2/2/2/2/2/2/2/2/4/...,23/23/26/24/18/13/15/14/17/20/24/30/23/25/22/1...
2,nia+404@rowan.kr,1.46875,401,2544,...,7297,2020-11-30T03:59:59+09:00,2020-11-29T04:00:00+09:00,0,586,...,34,89,41,62,0.07,0.07,21360,0/74/73/73/74/74/74/71/71/70/70/69/70/68/66/69...,4/2/4/4/1/1/1/4/4/4/4/4/4/4/2/3/4/2/2/4/2/2/2/...,0/11/14/20/13/14/14/16/27/29/27/20/19/19/14/12...
3,nia+404@rowan.kr,0.34375,27,1850,...,491,2020-12-01T03:59:59+09:00,2020-11-30T04:00:00+09:00,0,176,...,44,86,29,56,-0.41,-0.41,20100,73/70/71/72/75/75/73/70/70/70/67/63/63/63/63/6...,4/4/4/4/3/3/3/2/4/4/4/2/2/2/2/2/2/2/2/4/2/2/2/...,24/28/19/17/12/10/17/20/23/23/25/31/26/25/34/3...
4,nia+404@rowan.kr,1.46875,333,2518,...,5861,2020-12-02T03:59:59+09:00,2020-12-01T04:00:00+09:00,0,646,...,39,14,54,59,-0.27,-0.27,20730,0/0/0/0/0/0/0/0/69/69/71/69/65/66/64/64/65/66/...,4/4/4/4/4/4/4/4/4/4/4/2/2/2/2/3/3/2/4/4/4/2/2/...,0/0/0/0/0/0/0/0/21/22/26/23/19/29/22/17/14/13/...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2473,nia+280@rowan.kr,1.59375,648,2760,...,12256,2021-02-13T03:59:59+09:00,2021-02-12T04:00:00+09:00,0,444,...,90,89,22,25,-0.27,-0.27,12300,66/66/65/64/65/65/65/63/63/63/62/65/64/60/60/6...,4/2/4/4/2/2/2/2/3/2/1/1/2/2/1/1/1/1/1/1/3/2/2/...,45/35/29/27/34/30/31/32/41/40/37/28/43/46/53/4...
2474,nia+280@rowan.kr,1.43750,379,2507,...,6973,2021-02-14T03:59:59+09:00,2021-02-13T04:00:00+09:00,0,623,...,46,97,95,92,-0.13,-0.13,28800,66/0/0/69/69/69/67/65/63/63/64/64/66/70/66/65/...,4/2/4/2/1/4/2/2/2/1/1/1/1/4/2/2/2/2/3/3/3/3/3/...,21/0/0/30/31/35/35/29/37/34/35/35/31/15/20/23/...
2475,nia+280@rowan.kr,1.56250,670,2747,...,13008,2021-02-16T03:59:59+09:00,2021-02-15T04:00:00+09:00,0,422,...,51,81,62,85,0.21,0.21,27030,63/63/63/62/63/62/62/62/63/69/71/68/70/0/0/72/...,4/2/2/2/2/2/1/1/1/1/2/2/4/4/4/1/2/3/3/3/2/2/2/...,29/28/28/32/27/35/34/36/31/27/14/29/16/0/0/19/...
2476,nia+280@rowan.kr,1.46875,556,2570,...,11043,2021-02-17T03:59:59+09:00,2021-02-16T04:00:00+09:00,0,452,...,79,75,98,100,0.69,0.69,35910,0/72/71/70/68/69/69/68/68/0/0/0/68/68/68/68/67...,4/2/2/4/4/2/1/1/4/4/4/4/1/1/1/1/2/2/2/4/2/1/1/...,0/19/14/14/22/20/22/22/22/0/0/0/31/30/34/30/26...
2477,nia+280@rowan.kr,1.34375,311,2341,...,5943,2021-02-18T03:59:59+09:00,2021-02-17T04:00:00+09:00,0,595,...,90,86,23,74,-0.91,-0.91,24300,0/0/0/0/64/66/66/65/65/67/68/66/66/66/66/66/67...,4/4/4/4/2/2/2/1/1/1/1/2/2/2/1/1/2/3/2/2/2/2/2/...,0/0/0/0/25/31/33/35/36/33/17/30/30/29/31/29/23...

In [50]:
val_data=val_data.drop(val_data.columns[[4,13,39,42,52]], axis=1)
val_data

,EMAIL,activity_average_met,activity_cal_active,activity_cal_total,activity_daily_movement,activity_day_end,activity_day_start,activity_high,activity_inactive,activity_inactivity_alerts,...,sleep_score_efficiency,sleep_score_latency,sleep_score_rem,sleep_score_total,sleep_temperature_delta,sleep_temperature_deviation,sleep_total,CONVERT(sleep_hr_5min USING utf8),CONVERT(sleep_hypnogram_5min USING utf8),CONVERT(sleep_rmssd_5min USING utf8)
0,nia+404@rowan.kr,1.71875,730,2944,14346,2020-11-28T03:59:59+09:00,2020-11-27T04:00:00+09:00,0,417,0,...,27,97,66,62,-0.12,-0.12,21510,0/73/73/73/72/71/70/71/71/71/70/70/73/72/74/74...,4/2/4/3/3/1/2/2/2/2/2/2/3/3/3/4/4/3/2/2/2/2/2/...,0/10/10/10/11/11/10/12/18/13/14/12/10/10/18/17...
1,nia+404@rowan.kr,1.40625,342,2449,6352,2020-11-29T03:59:59+09:00,2020-11-28T04:00:00+09:00,0,473,0,...,46,91,35,44,-0.32,-0.32,17040,69/70/69/69/70/72/71/72/70/69/69/69/68/68/63/6...,2/4/2/2/2/2/3/1/2/2/4/4/2/2/2/2/2/2/2/2/2/2/4/...,23/23/26/24/18/13/15/14/17/20/24/30/23/25/22/1...
2,nia+404@rowan.kr,1.46875,401,2544,7297,2020-11-30T03:59:59+09:00,2020-11-29T04:00:00+09:00,0,586,0,...,34,89,41,62,0.07,0.07,21360,0/74/73/73/74/74/74/71/71/70/70/69/70/68/66/69...,4/2/4/4/1/1/1/4/4/4/4/4/4/4/2/3/4/2/2/4/2/2/2/...,0/11/14/20/13/14/14/16/27/29/27/20/19/19/14/12...
3,nia+404@rowan.kr,0.34375,27,1850,491,2020-12-01T03:59:59+09:00,2020-11-30T04:00:00+09:00,0,176,0,...,44,86,29,56,-0.41,-0.41,20100,73/70/71/72/75/75/73/70/70/70/67/63/63/63/63/6...,4/4/4/4/3/3/3/2/4/4/4/2/2/2/2/2/2/2/2/4/2/2/2/...,24/28/19/17/12/10/17/20/23/23/25/31/26/25/34/3...
4,nia+404@rowan.kr,1.46875,333,2518,5861,2020-12-02T03:59:59+09:00,2020-12-01T04:00:00+09:00,0,646,0,...,39,14,54,59,-0.27,-0.27,20730,0/0/0/0/0/0/0/0/69/69/71/69/65/66/64/64/65/66/...,4/4/4/4/4/4/4/4/4/4/4/2/2/2/2/3/3/2/4/4/4/2/2/...,0/0/0/0/0/0/0/0/21/22/26/23/19/29/22/17/14/13/...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2473,nia+280@rowan.kr,1.59375,648,2760,12256,2021-02-13T03:59:59+09:00,2021-02-12T04:00:00+09:00,0,444,0,...,90,89,22,25,-0.27,-0.27,12300,66/66/65/64/65/65/65/63/63/63/62/65/64/60/60/6...,4/2/4/4/2/2/2/2/3/2/1/1/2/2/1/1/1/1/1/1/3/2/2/...,45/35/29/27/34/30/31/32/41/40/37/28/43/46/53/4...
2474,nia+280@rowan.kr,1.43750,379,2507,6973,2021-02-14T03:59:59+09:00,2021-02-13T04:00:00+09:00,0,623,0,...,46,97,95,92,-0.13,-0.13,28800,66/0/0/69/69/69/67/65/63/63/64/64/66/70/66/65/...,4/2/4/2/1/4/2/2/2/1/1/1/1/4/2/2/2/2/3/3/3/3/3/...,21/0/0/30/31/35/35/29/37/34/35/35/31/15/20/23/...
2475,nia+280@rowan.kr,1.56250,670,2747,13008,2021-02-16T03:59:59+09:00,2021-02-15T04:00:00+09:00,0,422,0,...,51,81,62,85,0.21,0.21,27030,63/63/63/62/63/62/62/62/63/69/71/68/70/0/0/72/...,4/2/2/2/2/2/1/1/1/1/2/2/4/4/4/1/2/3/3/3/2/2/2/...,29/28/28/32/27/35/34/36/31/27/14/29/16/0/0/19/...
2476,nia+280@rowan.kr,1.46875,556,2570,11043,2021-02-17T03:59:59+09:00,2021-02-16T04:00:00+09:00,0,452,2,...,79,75,98,100,0.69,0.69,35910,0/72/71/70/68/69/69/68/68/0/0/0/68/68/68/68/67...,4/2/2/4/4/2/1/1/4/4/4/4/1/1/1/1/2/2/2/4/2/1/1/...,0/19/14/14/22/20/22/22/22/0/0/0/31/30/34/30/26...
2477,nia+280@rowan.kr,1.34375,311,2341,5943,2021-02-18T03:59:59+09:00,2021-02-17T04:00:00+09:00,0,595,0,...,90,86,23,74,-0.91,-0.91,24300,0/0/0/0/64/66/66/65/65/67/68/66/66/66/66/66/67...,4/4/4/4/2/2/2/1/1/1/1/2/2/2/1/1/2/3/2/2/2/2/2/...,0/0/0/0/25/31/33/35/36/33/17/30/30/29/31/29/23...

In [51]:
val_data = val_data.loc[:,~val_data.columns.duplicated()] # 중복되는 EMAIl 열 하나만 남기고 하나만 제거
val_data

,EMAIL,activity_average_met,activity_cal_active,activity_cal_total,activity_daily_movement,activity_day_end,activity_day_start,activity_high,activity_inactive,activity_inactivity_alerts,...,sleep_score_efficiency,sleep_score_latency,sleep_score_rem,sleep_score_total,sleep_temperature_delta,sleep_temperature_deviation,sleep_total,CONVERT(sleep_hr_5min USING utf8),CONVERT(sleep_hypnogram_5min USING utf8),CONVERT(sleep_rmssd_5min USING utf8)
0,nia+404@rowan.kr,1.71875,730,2944,14346,2020-11-28T03:59:59+09:00,2020-11-27T04:00:00+09:00,0,417,0,...,27,97,66,62,-0.12,-0.12,21510,0/73/73/73/72/71/70/71/71/71/70/70/73/72/74/74...,4/2/4/3/3/1/2/2/2/2/2/2/3/3/3/4/4/3/2/2/2/2/2/...,0/10/10/10/11/11/10/12/18/13/14/12/10/10/18/17...
1,nia+404@rowan.kr,1.40625,342,2449,6352,2020-11-29T03:59:59+09:00,2020-11-28T04:00:00+09:00,0,473,0,...,46,91,35,44,-0.32,-0.32,17040,69/70/69/69/70/72/71/72/70/69/69/69/68/68/63/6...,2/4/2/2/2/2/3/1/2/2/4/4/2/2/2/2/2/2/2/2/2/2/4/...,23/23/26/24/18/13/15/14/17/20/24/30/23/25/22/1...
2,nia+404@rowan.kr,1.46875,401,2544,7297,2020-11-30T03:59:59+09:00,2020-11-29T04:00:00+09:00,0,586,0,...,34,89,41,62,0.07,0.07,21360,0/74/73/73/74/74/74/71/71/70/70/69/70/68/66/69...,4/2/4/4/1/1/1/4/4/4/4/4/4/4/2/3/4/2/2/4/2/2/2/...,0/11/14/20/13/14/14/16/27/29/27/20/19/19/14/12...
3,nia+404@rowan.kr,0.34375,27,1850,491,2020-12-01T03:59:59+09:00,2020-11-30T04:00:00+09:00,0,176,0,...,44,86,29,56,-0.41,-0.41,20100,73/70/71/72/75/75/73/70/70/70/67/63/63/63/63/6...,4/4/4/4/3/3/3/2/4/4/4/2/2/2/2/2/2/2/2/4/2/2/2/...,24/28/19/17/12/10/17/20/23/23/25/31/26/25/34/3...
4,nia+404@rowan.kr,1.46875,333,2518,5861,2020-12-02T03:59:59+09:00,2020-12-01T04:00:00+09:00,0,646,0,...,39,14,54,59,-0.27,-0.27,20730,0/0/0/0/0/0/0/0/69/69/71/69/65/66/64/64/65/66/...,4/4/4/4/4/4/4/4/4/4/4/2/2/2/2/3/3/2/4/4/4/2/2/...,0/0/0/0/0/0/0/0/21/22/26/23/19/29/22/17/14/13/...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2473,nia+280@rowan.kr,1.59375,648,2760,12256,2021-02-13T03:59:59+09:00,2021-02-12T04:00:00+09:00,0,444,0,...,90,89,22,25,-0.27,-0.27,12300,66/66/65/64/65/65/65/63/63/63/62/65/64/60/60/6...,4/2/4/4/2/2/2/2/3/2/1/1/2/2/1/1/1/1/1/1/3/2/2/...,45/35/29/27/34/30/31/32/41/40/37/28/43/46/53/4...
2474,nia+280@rowan.kr,1.43750,379,2507,6973,2021-02-14T03:59:59+09:00,2021-02-13T04:00:00+09:00,0,623,0,...,46,97,95,92,-0.13,-0.13,28800,66/0/0/69/69/69/67/65/63/63/64/64/66/70/66/65/...,4/2/4/2/1/4/2/2/2/1/1/1/1/4/2/2/2/2/3/3/3/3/3/...,21/0/0/30/31/35/35/29/37/34/35/35/31/15/20/23/...
2475,nia+280@rowan.kr,1.56250,670,2747,13008,2021-02-16T03:59:59+09:00,2021-02-15T04:00:00+09:00,0,422,0,...,51,81,62,85,0.21,0.21,27030,63/63/63/62/63/62/62/62/63/69/71/68/70/0/0/72/...,4/2/2/2/2/2/1/1/1/1/2/2/4/4/4/1/2/3/3/3/2/2/2/...,29/28/28/32/27/35/34/36/31/27/14/29/16/0/0/19/...
2476,nia+280@rowan.kr,1.46875,556,2570,11043,2021-02-17T03:59:59+09:00,2021-02-16T04:00:00+09:00,0,452,2,...,79,75,98,100,0.69,0.69,35910,0/72/71/70/68/69/69/68/68/0/0/0/68/68/68/68/67...,4/2/2/4/4/2/1/1/4/4/4/4/1/1/1/1/2/2/2/4/2/1/1/...,0/19/14/14/22/20/22/22/22/0/0/0/31/30/34/30/26...
2477,nia+280@rowan.kr,1.34375,311,2341,5943,2021-02-18T03:59:59+09:00,2021-02-17T04:00:00+09:00,0,595,0,...,90,86,23,74,-0.91,-0.91,24300,0/0/0/0/64/66/66/65/65/67/68/66/66/66/66/66/67...,4/4/4/4/2/2/2/1/1/1/1/2/2/2/1/1/2/3/2/2/2/2/2/...,0/0/0/0/25/31/33/35/36/33/17/30/30/29/31/29/23...

In [52]:
val_merged_data = pd.merge(val_data, val_think, left_on='EMAIL', right_on='SAMPLE_EMAIL', how='inner')
val_merged_data

,EMAIL,activity_average_met,activity_cal_active,activity_cal_total,activity_daily_movement,activity_day_end,activity_day_start,activity_high,activity_inactive,activity_inactivity_alerts,...,Q14_1,Q14_2,Q15,Q16_1,Q16_2,Q16_3,Q17,Q18,Q19,TOTAL
0,nia+404@rowan.kr,1.71875,730,2944,14346,2020-11-28T03:59:59+09:00,2020-11-27T04:00:00+09:00,0,417,0,...,2,2,2,2,2,2,2,2,2,29
1,nia+404@rowan.kr,1.40625,342,2449,6352,2020-11-29T03:59:59+09:00,2020-11-28T04:00:00+09:00,0,473,0,...,2,2,2,2,2,2,2,2,2,29
2,nia+404@rowan.kr,1.46875,401,2544,7297,2020-11-30T03:59:59+09:00,2020-11-29T04:00:00+09:00,0,586,0,...,2,2,2,2,2,2,2,2,2,29
3,nia+404@rowan.kr,0.34375,27,1850,491,2020-12-01T03:59:59+09:00,2020-11-30T04:00:00+09:00,0,176,0,...,2,2,2,2,2,2,2,2,2,29
4,nia+404@rowan.kr,1.46875,333,2518,5861,2020-12-02T03:59:59+09:00,2020-12-01T04:00:00+09:00,0,646,0,...,2,2,2,2,2,2,2,2,2,29
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2473,nia+280@rowan.kr,1.59375,648,2760,12256,2021-02-13T03:59:59+09:00,2021-02-12T04:00:00+09:00,0,444,0,...,2,2,2,2,2,2,2,2,2,29
2474,nia+280@rowan.kr,1.43750,379,2507,6973,2021-02-14T03:59:59+09:00,2021-02-13T04:00:00+09:00,0,623,0,...,2,2,2,2,2,2,2,2,2,29
2475,nia+280@rowan.kr,1.56250,670,2747,13008,2021-02-16T03:59:59+09:00,2021-02-15T04:00:00+09:00,0,422,0,...,2,2,2,2,2,2,2,2,2,29
2476,nia+280@rowan.kr,1.46875,556,2570,11043,2021-02-17T03:59:59+09:00,2021-02-16T04:00:00+09:00,0,452,2,...,2,2,2,2,2,2,2,2,2,29
2477,nia+280@rowan.kr,1.34375,311,2341,5943,2021-02-18T03:59:59+09:00,2021-02-17T04:00:00+09:00,0,595,0,...,2,2,2,2,2,2,2,2,2,29

In [53]:
val_merged_data.drop(['DOCTOR_NM'], axis=1, inplace=True)
val_merged_data

,EMAIL,activity_average_met,activity_cal_active,activity_cal_total,activity_daily_movement,activity_day_end,activity_day_start,activity_high,activity_inactive,activity_inactivity_alerts,...,Q14_1,Q14_2,Q15,Q16_1,Q16_2,Q16_3,Q17,Q18,Q19,TOTAL
0,nia+404@rowan.kr,1.71875,730,2944,14346,2020-11-28T03:59:59+09:00,2020-11-27T04:00:00+09:00,0,417,0,...,2,2,2,2,2,2,2,2,2,29
1,nia+404@rowan.kr,1.40625,342,2449,6352,2020-11-29T03:59:59+09:00,2020-11-28T04:00:00+09:00,0,473,0,...,2,2,2,2,2,2,2,2,2,29
2,nia+404@rowan.kr,1.46875,401,2544,7297,2020-11-30T03:59:59+09:00,2020-11-29T04:00:00+09:00,0,586,0,...,2,2,2,2,2,2,2,2,2,29
3,nia+404@rowan.kr,0.34375,27,1850,491,2020-12-01T03:59:59+09:00,2020-11-30T04:00:00+09:00,0,176,0,...,2,2,2,2,2,2,2,2,2,29
4,nia+404@rowan.kr,1.46875,333,2518,5861,2020-12-02T03:59:59+09:00,2020-12-01T04:00:00+09:00,0,646,0,...,2,2,2,2,2,2,2,2,2,29
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2473,nia+280@rowan.kr,1.59375,648,2760,12256,2021-02-13T03:59:59+09:00,2021-02-12T04:00:00+09:00,0,444,0,...,2,2,2,2,2,2,2,2,2,29
2474,nia+280@rowan.kr,1.43750,379,2507,6973,2021-02-14T03:59:59+09:00,2021-02-13T04:00:00+09:00,0,623,0,...,2,2,2,2,2,2,2,2,2,29
2475,nia+280@rowan.kr,1.56250,670,2747,13008,2021-02-16T03:59:59+09:00,2021-02-15T04:00:00+09:00,0,422,0,...,2,2,2,2,2,2,2,2,2,29
2476,nia+280@rowan.kr,1.46875,556,2570,11043,2021-02-17T03:59:59+09:00,2021-02-16T04:00:00+09:00,0,452,2,...,2,2,2,2,2,2,2,2,2,29
2477,nia+280@rowan.kr,1.34375,311,2341,5943,2021-02-18T03:59:59+09:00,2021-02-17T04:00:00+09:00,0,595,0,...,2,2,2,2,2,2,2,2,2,29

In [54]:
val_merged_data.to_csv("C:/Users/82102/Desktop/의료/128.치매 고위험군 라이프로그/128.치매 고위험군 라이프로그/01.데이터/val_data.csv")